reviews_text<-readLines('/home/sunil/Desktop/sentiment_analysis/amazon _reviews_polarity.csv', n = 1000)
print("EDA PRIOR TO PROCESSING")
print(class(reviews_text))
print(length(reviews_text))
print(head(reviews_text,2))
reviews_text<-gsub("\\\"2\\\",","__label__2 ",reviews_text)
reviews_text<-gsub("\\\"1\\\",","__label__1 ",reviews_text)
reviews_text<-gsub("\\\""," ",reviews_text)
reviews_text<-gsub("(?<=[\\s])\\s*|^\\s+|\\s+$", "", reviews_text, perl=TRUE)
print("EDA POST TO PROCESSING")
print(class(reviews_text))
print(length(reviews_text))
print(head(reviews_text,2))
fileConn<-file("/home/sunil/Desktop/sentiment_analysis/Sentiment Analysis Dataset_ft.txt")
writeLines(reviews_text, fileConn)
close(fileConn)