setwd('/home/sunil/Desktop/chapter5/')
cust_data = read.csv(file='Wholesale_customers_ data.csv', header = TRUE)
print(dim(cust_data))
View(cust_data)
print(apply(cust_data, 2, function (x) sum(is.na(x))))
print(summary(cust_data))
library(dbscan)
kNNdistplot(cust_data, k = 6)
abline(h = 7000, col = "red", lty = 2)
results <- dbscan(cust_data, eps = 7000, minPts = 6)
print(results)
hullplot(cust_data, results)